### ISSUE TITLE
add a document detailing how to spin up postgres for PIP work

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-cookbook#24]
Detail how to spin up a postgres database for PIP work. Also include info on in-memory rtree pip server.

Add links to that from the following README files:
- https://github.com/whosonfirst/go-whosonfirst-pgis/blob/master/README.md
- https://github.com/whosonfirst/py-mapzen-whosonfirst-spatial/blob/master/README.md
- https://github.com/whosonfirst/py-mapzen-whosonfirst-hierarchy/blob/master/README.md

**Comment by stepps00** [comment]
Done here:

https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/how_to/setting_up_pip_service.md

Will probably need updates at some point, but workable for now.

**Comment by nvkelso** [comment]
Can you add issue to track making that line cmd configurable (last paragraph), please?

**Comment by stepps00** [comment]
@nvkelso - added: https://github.com/whosonfirst/go-whosonfirst-pgis/issues/11
