### ISSUE TITLE
Create doc with placetype counts per country

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-cookbook#39]
Similar to [the placetypes by country table](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/definition/placetypes_by_country.md), it would be nice to have a sheet with per-country record counts per placetype.

I have the data (which can also be found browsing the Spelunker), it is just a matter of converting it to a markdown table and adding a new markdown file to this repo.

**Comment by thisisaaronland** [comment]
FYI, this probably doesn't do exactly what you need to but could - https://github.com/whosonfirst/go-whosonfirst-stats

The benefit of this package is that it uses the `whosonfirst/go-whosonfirst-index` package under the hood so it can read from the local filesystem and GitHub and others.
