### ISSUE TITLE
Document `wof:controlled` logic for neighbourhood updates

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-cookbook#8]
Articulate logic for the `wof:controlled` code in neighbourhood updates, link to it in the code and vice versa.

Specifically, https://github.com/whosonfirst/py-mapzen-whosonfirst-hierarchy/blob/master/mapzen/whosonfirst/hierarchy/__init__.py#L54-L62.

There are some interesting cases (Edmonton) where the code acts unexpectedly - document these rules for future/outsider reference.

**Comment by thisisaaronland** [comment]
cc @dphiffer because he will need to care about (or at least be aware of) these details.
